name: Terraform CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
jobs:
  plan:
    name: Terraform - fmt / validate / plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform fmt (check)
        run: terraform fmt -check
        working-directory: filestf/eks

      - name: Terraform init
        run: terraform init
        working-directory: filestf/eks

      - name: Terraform validate
        run: terraform validate
        working-directory: filestf/eks

      - name: Terraform plan (save plan file)
        run: terraform plan -out=tfplan
        working-directory: filestf/eks

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: filestf/eks/tfplan

  apply:
    name: Terraform - apply (requires approval)
    needs: plan
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: filestf/eks

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform apply (using saved plan)
        run: terraform apply -input=false tfplan
        working-directory: filestf/eks
